### ISSUE TITLE
decor/sniff: platform detection should be uncoupled from  "webkit" detection

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/decor#30]
Currently, has("android") returns undefined on any non-webkit browser on Android (for instance, Firefox / Nexus 5 / Android 5) and has("ios") returns undefined on any non-webkit browser on iOS. This is because https://github.com/ibm-js/decor/blob/master/sniff.js runs the platform detection for Android and iOS only if the browser is found to be a webkit browsers.

Regardless of whether we support some combination of browser and platform, I think it would be saner to uncouple the platform detection from the webkit detection. At least I don't see a good reason to keep it coupled.

**Comment by wkeese** [comment]
Agreed, makes sense.
