### ISSUE TITLE
Stateful: Getting an exception when initializing a widget.

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/decor#32]
Since the commit https://github.com/ibm-js/decor/commit/51afb50a6b5c80d0c915ae21bf9ad2b8335744b3 was introduced, I can't seem to be able to initialize a widget: I keep getting theses exceptions.
![image](https://cloud.githubusercontent.com/assets/2982512/5755491/5c05bb06-9ca5-11e4-97d8-aa5e1ef72b51.png)
You can reproduce it by loading any sample from delite or deliteful.

**Comment by cjolif** [comment]
are you 100% sure you have the right set of dependencies? i.e. you have updated delite & deliteful to recent version that contain adjustments for this?

**Comment by tkrugg** [comment]
delite was a few commits behind indeed, thanks.
