### ISSUE TITLE
events: event handle by type? 

### ISSUE THREAD

**Issue by mc007** [ibm-js/decor#38]
Hi,
there seems to be the same problem as in Dijit (dijit/_AttachMixin): you can't get the handle for on('click') when you didn't created it yourself(parsed). I know that's a common problem, see http://stackoverflow.com/questions/446892/how-to-find-event-listeners-on-a-dom-node. Please just close the issue if this out of your scope or not a requirement to you. 

A more elegant way I could figure out in general is to extend the Evented mixin for 

@type {map of keys and handlers/structs}
emits:{}

@type {map of keys and handlers/structs}
subscribes:{}

This could also enable event filtering and better intro-spection, for instance you could silence a widget for "delite-activated" by setting emits['delite-activated']=false or similar. Just an idea, but it turned out well for me.

**Comment by wkeese** [comment]
I can't follow what you are talking about.   Is this ticket about decor/Evented?

**Comment by mc007** [comment]
i wrote 2 things, a problem, and a possible solution. 

the problem: I can't  query widgets for event handles like click,.. or widget events 'delite-activated' 
because I didn't create this handles. 

I am not really in delite yet, but if decor/Evented is in charge to register event handlers, then the idea is too make it track the information: eventType|handler ( on('click'),fn). Only that way I can get the handle at any time I want. 
thank you

**Comment by cjolif** [comment]
decor/Evented is not used in delite/Widget. This class is for non DOM-element event management. On DOM elements (like delite/Widget) even though we provide shortcut methods like `on` the underlying eventing mechanism is "just" DOM one (i.e. addEventListener...).

**Comment by mc007** [comment]
ok, thank you both. 
So if there is one way to get the event the event-handles, for both, non-widgets and dom-handle, please let me know. Looks like I need to fork decor/delite. Possibly my use-cases are out of the normal:
- replace event handlers
- silence/filter/remove event handlers, eg:  for re-using widgets, or suspend them, etc...
g

**Comment by wkeese** [comment]
Ah, I see what you mean now.  You want some function like `getListeners()` that returns data about every listener registered by `Evented#on()` (or `Widget#on()`).

Hmm, probably that's out of scope for us, although it's worth thinking about it.   This reminds me a bit of namespaces in jQuery (http://api.jquery.com/off/).

**Comment by mc007** [comment]
Yes please, Bill :-) 

Doing event 'filtering' that way at this level saves me from doing lots of code in my app. And not only this: it could enable to 'suspend' and 'resume' a widget, or simply re-using it, since re-creation involves far more computations. 

I am not sure about the right data structure yet for the event-handler tracking but this here could do the job.

```javascript
Evented::emits : {
        handlers: [
            {type: 'click', handler: fn},
            {type: 'click', handler: fn}
        ],
        disabled:{
            'click':null
        },
        can: function (type) {
            return !type in this.disabled;
        },
        whateverAPI...
    }
```
I've got a naive version working and it solves me lots of problems. For instance I can pass the black list already along with the constructor args and when needed, you could call widget.registerEventHandlers as part of widget.resume()...

thanks for the heads up.

**Comment by wkeese** [comment]
> it could enable to 'suspend' and 'resume' a widget

Well, I'm not sure what you mean exactly by "suspend", but note that widgets can set up listeners directly (by calling addEventListener()), so a list of calls to Evented#on() (or Widget#on()) isn't a complete list of everything.

Also, note that "handle" and "listener" are two different things.  A listener (aka callback) is the function passed as the second parameter to on(), whereas a "handle" is the opaque return value from on().

**Comment by mc007** [comment]
Ok, now I start understanding that delite/delitful is really a thin layer, closely tied to native HTML and so leaving me no choice but patching the addEventListener prototype and route it over something like 'on' to get a handle and the type ('click'). This is primarily for 'optimization' tasks but also to make 'authoring' of 'behaviors' possible, in a real-time IDE: https://raw.githubusercontent.com/mc007/xbox-app/master/misc/screenshots/x17.png. Having unified access to all user created (attribute/code) (not widget internals) handles/listeners per types would be awesome but absolutely necessary. 

By 'suspending' a widget I mean: freeze it for real(catch bad user code) or just silence what i want or replace handlers for 'click/over/...'.  That's also for caching widgets and really makes a noticeably difference in a large ui (20+ sliders/buttons per tab...). 

well, hope that makes some sense ;-) In 

thanks again Bill.

g

**Comment by mc007** [comment]
I found a working (so lala) implementation of 'XBL 2.0':  http://code.google.com/p/xbl/ which has been taken as input to delite the HTML-Custom-Element specification: http://www.w3.org/TR/custom-elements/. 

That seems to fit my purpose of adding behaviors in a more fashioned way, also adding a little more than liason does. This doesn't gives me 'off' as in jQuery nor I get the event handler/handle per type through decor/delite, but it worth a shot, possibly there is no need for me anymore in this matter. 

I will let you how it goes, if you like. Thanks again.
g

**Comment by wkeese** [comment]
> Ok, now I start understanding that delite/delitful is really a thin layer, closely tied to native HTML and so leaving me no choice but patching the addEventListener prototype 

Yes, probably that's true.   Especially since application code may call `myWidget.addEventListener()` rather than `myWidet.on()`.

> I found a working (so lala) implementation of 'XBL 2.0'

OK, I hope that works for you, although I notice that it's been abandoned.

In any case I guess we should close this ticket.
