### ISSUE TITLE
call deliver() automatically for Invalidating

### ISSUE THREAD

**Issue by wkeese** [ibm-js/decor#40]
Complementary to ibm-js/delite#385, we should probably call deliver() automatically when an Invalidating subclass has been instantiated.

**Comment by wkeese** [comment]
Hmm, now I'm confused.   Unlike delite/Widget, the values passed to an Invalidating's subclasses constructor don't seem to trigger a call to refreshRendering().  @asudoh, @cjolif do you know if this is intentional?

I put my attempted fix at https://github.com/wkeese/decor/tree/invalidating-auto-deliver but it doesn't work because of this discrepancy.

**Comment by cjolif** [comment]
In my first versions that was definitely intentional as initial setting of the properties were considered dealt in buildRendering(). After that I must admit lost track... Anyway we must be very cautious with any change here as I suspect it might well break deliteful or other component.

**Comment by wkeese** [comment]
> In my first versions that was definitely intentional as initial setting of the properties were considered dealt in buildRendering(). 

I understand that philosophy but we should change it because it's inconsistent with delite/CustomElement.   Plus which it's often convenient to consolidate property-related rendering code into refreshRendering().  Agreed?

> Anyway we must be very cautious with any change here as I suspect it might well break deliteful or other component.

Sure, that's possible, although it would only affect modules that extend decor/Invalidating w/out extending delite/CustomElement, and AFAICT there are no such modules?  delite/Store and delite/StoreMap fit that description, but they are just base classes used by other modules.

The real question is whether we should do it for 0.7 or 0.8.
