### ISSUE TITLE
Return of Observable.observe.remove()

### ISSUE THREAD

**Issue by harbalk** [ibm-js/decor#50]
The function remove of the result of Observable.observe return the object where the observability has been removed on native implementation of Chrome.
It is not the case of the one define in Observable.js.

I do not know if it is wanted or not, but it is quite useful in Chrome to test if we have removed the observability on the good object.

See test Store-ArrayObs in https://github.com/harbalk/delite/commit/46e3e5c19c5b621abe8a6b2de3b7a20c9ba2f86f
```
assert.deepEqual(store._itemHandles[0].remove(), { id: "bar", name: "Bar" });
assert.deepEqual(store._itemHandles[1].remove(), { id: "fb", name: "FB" });
```

**Comment by asudoh** [comment]
Create [a PR](https://github.com/ibm-js/decor/pull/51), which does the way around, in order to align to other `remove()` implementations (and `close()` in [Polymer/observe-js](https://github.com/polymer/observe-js)).
