### ISSUE TITLE
dont wrap widget methods? 

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/decor#59]
Hi,
I noticed that all my custom widget's methods are wrapped by decor/Stateful#introspect. I'd understand this for properties but not for functions which don't use get/set prefixes or similar. 

Might it be possible to suppress this behavior? 

thanks a lot

**Comment by wkeese** [comment]
Actually that's how it worked initially, but I got complaints that people might change functions on the fly too (because functions are properties, just not scalar properties).  See ibm-js/delite#314.

But you should be able to customize the behavior by overriding `getProps()`.

**Comment by gbaumgart** [comment]
ok, thanks Bill, that will do too.
